### ISSUE TITLE
True collaboration without web editor

### ISSUE THREAD

**Issue by lorenzschmid** [standardnotes/collab-editor#2]
While switching between the plain and the collaboration editor back and forth I discovered that the content of the note all of a sudden contains a header:

    id: XXXX
    key: XXXX
    %%Do not modify above this line%%
    ...

This for sure could be hidden by the plain text editor but storing these information in the note itself mixes meta data and content which should be avoided. My idea for an alternative implementation:

As soon as a note should be shared the editor is actually creating two items in the database:

 - the first representing a note (type `note`) without association to any user and therefore encrypted with a new key (as for the current shared notes)
 - the second of the new type `shared` linked to the author, referencing the note above (`references`) and containing only the encryption key

This allows other users to add this note to their "notebook" by simply creating another, personal `shared` item pointing to the same note. Of course this also nicely separates the above mentioned mixing of metadata and content and would allow to skip the web editor. Exchanging of key and link could work similarly as already implemented.

**Comment by atmoio** [comment]
I'm not sure I'm following. I'm losing context of where your idea would take place. In the Standard Notes app, or by the 3rd party editor? When you say two items are created in the database, whose database are you referring to - Standard Notes data, or 3rd party database?

And how does this avoid metadata?

**Comment by lorenzschmid** [comment]
I'm sorry, I must have written down a bit too quickly.

Looking at the current implementation I am not sure to understand how the decryption of the collaborative works. It looks like all my notes (collaborative or not) are encrypted with the same key. So as soon as I want to collaborate on one of the notes I need to pass on either my encryption key (and therefore indirectly expose all my notes) or a new key is created specific for this collaborative note - but I don't currently see where it is stored (at the beginning of the note?). Maybe you can give me some insights on this?

What I tried to point out is a solution to the problem just described - but I must admit that I wrote it without fully understanding your current implementation, sorry. To conclude, I don't like the idea of:

 - de-/encryption in the browser (instead of a signed app)
 - having metadata in my note (aka `%%Do not modify above this line%%` - I didn't mean metadata in the sense of "who is collaborating with who")
 - having an editor in an editor (CodeMirror in Standard Note)

What I think could be a solution is:

Having a `note` item in the Standard Notes database which is not related to any user and has its individual encryption key. All users who then want to collaborate on this note have their own "pointer" item (e.g. `shared` item, also stored in the Standard Notes database). It contains a reference to the unbound `note` item as well as the encryption key for it.
When my local Standard Notes app fetches my data it then gets all my `note` and `shared`/pointer items. Upon decryption of the items it performs a second fetch to get all the collaborative note items pointed to by the pointer items. I can then work on this collaborative note as on any other note.

Let me know what your think and especially if I got your current implementation right.

**Comment by atmoio** [comment]
That won't work. Editors are extensions, and thus should not and do not have influence over what data Standard Notes stores (besides plaintext in the current note). Also, Standard Notes should not know or care what the editor does. You're suggesting making the Standard Notes app *aware* of a collaborative editor, but that means that it is no longer an extension, but custom behavior, which means complexity, which goes against what SN stands for.

**Comment by lorenzschmid** [comment]
Thanks a lot for your explanations. I like how you keep SN simple.

One last question: Don't you think the Standard *Files* protocol would profit from universal sharing/collaborating implementation (e.g. as described above) which is then common to all its apps (i.e. the SN app)?

**Comment by atmoio** [comment]
That's a good point. At this point, I would say it's not a priority. But who knows what the future holds :)

**Comment by atmoio** [comment]
The metadata issue has been fixed with the latest release. Each editor can now save custom data behind the scenes and sync it with the user's account. Simple change: https://github.com/standardnotes/web/pull/84/files
