### ISSUE TITLE
Collab-notes remain active after StandardNotes app switches back to plain editor

### ISSUE THREAD

**Issue by CR0CKER** [standardnotes/collab-editor#5]
I can continue to edit a note on the collaboration-extension after switching back to plain editor in the desktop app. Collab notes should be removed from the extension when the desktop app stops using the extension for a note.

**Comment by atmoio** [comment]
Can you elaborate? Not exactly sure what you mean.

**Comment by CR0CKER** [comment]
If I create a note in the plain editor of the desktop app, and then select "Collaborative Editor", I get a read-only and an edit link that someone can access via web browser. If I copy that URL and later "un-collaborate" the note in my desktop app by switching back to the plain editor, the person who knows the URL can continue to access the note and make edits, without knowing that I am not editing it anymore, and without me being able to remove the shared version of that note.

**Comment by atmoio** [comment]
Collaboration editor is not aware of what you do in Standard Notes. Switching editors does not imply you've "closed" collaboration. So this would be technically impossible if we are to keep a separation of concerns.

**Comment by CR0CKER** [comment]
Hmm, how would I delete content from the collaboration editor then?

Also, if I switch to plain and then back to collab, it doesn't give me access to the originally shared content.

**Comment by CR0CKER** [comment]
I was wondering why there are so few open issues in this project -- now I know ;)
