### ISSUE TITLE
Allow for shared notes across several accounts 

### ISSUE THREAD

**Issue by CR0CKER** [standardnotes/collab-editor#6]
Sharing notes across StandardNotes.org accounts would make for a great addition to the collaboration editor.

**Comment by atmoio** [comment]
The collaboration editor is a separate entity from Standard Notes, and does not know or care about the inner workings of SN. There has to be a separation of concerns to protect SN from complexity. 

The only way to accomplish what you're asking for is for the collaboration editor, as its own separate entity, to create its own user account system to allow for sharing.

This is technically possible, but as this editor is still in its infancy, not a priority.
